name: Deploy Lambda Function

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy-preliminary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        run: |
          sudo apt-get install zip && sudo apt-get install unzip
      - name: Create Zip file for lambda Function
        run:  zip -r terraform-script .
      - name: AWS CLI v2
        run: |
          sudo apt-get install python3-pip && \
          sudo pip install awscli && \
          aws --version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_KEY: ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: "us-east-1"    

  deploy-dev:
      needs: [deploy-preliminary]
      if: github.ref == 'refs/heads/dev'
      
      runs-on: ubuntu-latest
      environment:
        name: development
        url: https://github.com/${{ github.repository }}/releases/tag/$v${{ vars.DEV_VERSION }}

      steps:
        - name: Download candidate artifacts
          uses: actions/download-artifact@v3
          with:
              name: Dockerfile

        - name: release to dev
          uses: softprops/action-gh-release@v0.1.15
          with:
            tag_name: v${{ vars.DEV_VERSION }}
            token: ${{ secrets.DEV_TOKEN }}
            prerelease: true
            draft: true
            name: dev



