name: Deploy Lambda Function

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy-preliminary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for lambda Function
        run:  zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "sts get-caller-identity"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_KEY: ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: "us-east-1"         


