name: Deploy Lambda Function

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy-preliminary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for lambda Function
        run: zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code 
            -- function-name arn:aws: ${{ provide your function ARN Here }} 
            -- zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_KEY: ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: "us-east-1"         

  deploy-dev:
      needs: [deploy-preliminary]
      if: github.ref == 'refs/heads/dev'
      
      runs-on: ubuntu-latest
      environment:
        name: development
        url: https://github.com/${{ github.repository }}/releases/tag/$v${{ vars.DEV_VERSION }}

      steps:
        - name: Download candidate artifacts
          uses: actions/download-artifact@v3
          with:
            name: archive.zip

       - name: release to dev
          uses: softprops/action-gh-release@v0.1.15
          with:
            tag_name: v${{ vars.DEV_VERSION }}
            token: ${{ secrets.DEV_TOKEN }}
            prerelease: true
            draft: true
            name: dev
            files: greetings-deploy.jar

  deploy-prod:
      needs: [deploy-preliminary]
      if: github.ref == 'refs/heads/main'
      
      runs-on: ubuntu-latest
      environment: 
        name: production
        url: https://github.com/${{ github.repository }}/releases/tag/$v${{ vars.PROD_VERSION }}
      steps: 
        - name: Download candidate artifacts
          uses: actions/download-artifact@v3
            with: 
              name: archive.zip
        - name: GH Release
          uses: softprops/action-gh-release@v0.1.15
            with:
              tag_name: v${{ PROD_VERSION }}
              token: ${{ secrets.PROD_TOKEN }}
              generate_release_notes: true
              name: Production
              files: greeting-deploy.jar
