name: Deploy Lambda Function

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy-preliminary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install zip tool, pylint and other dependencies
        run: |
          sudo apt-get install zip && \
          sudo apt-get install unzip && \
          sudo apt-get install pylint && \
          sudo apt-get install jq
          
      - name: Create Zip file for lambda Function
        run:  zip -r terraform-script .
      
      - name: AWS CLI v2
        run: |
          sudo apt-get install python3-pip && \
          sudo pip install awscli && \
          aws --version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_KEY: ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: "us-east-1" 
        
      - name: Testing Pylinting is installed
        run: pylint --version 

  deploy-dev:
      needs: [deploy-preliminary]
      if: github.ref == 'refs/heads/dev'
      
      runs-on: ubuntu-latest
      environment:
        name: development
        url: https://github.com/${{ github.repository }}/releases/tag/$v${{ vars.DEV_VERSION }}

      steps:
        - name: Download candidate artifacts
          uses: actions/upload-artifact@v4
          with:
              name: Dockerfile
              path: ${{ github.repository }}/.vscode/terraform-script

        


